grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 5
    verbose: 2
model_selection:
  module_0:
    class: KNeighborsClassifier
    module: sklearn.neighbors 
    params:
      fit_intercept: true
    search_param_grid:
      fit_intercept:
      - true
      - false
  module_1:
    class: LinearSVC
    module: sklearn.svm
    params:
      min_samples_leaf: 3
    search_param_grid:
      min_samples_leaf:
  module_2:
    class: DecisionTreeClassifier
    module: sklearn.tree
    params:
      fit_intercept: true
    search_param_grid:
      fit_intercept:
      - true
      - false
  module_3:
    class: AdaBoostClassifier
    module: sklearn.ensemble
    params:
      min_samples_leaf: 3
    search_param_grid:
      min_samples_leaf:
  module_4:
    class: RandomForestClassifier
    module: sklearn.ensemble 
    params:
      fit_intercept: true
    search_param_grid:
      fit_intercept:
      - true
      - false
  module_5:
    class: GaussianNB
    module: sklearn.naive_bayes
    params:
      min_samples_leaf: 3
    search_param_grid:
      min_samples_leaf:
 
